### ISSUE TITLE
I tried to open up the game, but as soon as something got opened, the game didn't run.

### ISSUE THREAD

**Issue by Brad2024** [EndersteveGamer/Friday-night-funkin-with-Pygame#1]
I tried to open up the game, but as soon as something got opened, the game didn't run. I tried running it in Python, and apparently something along hte lines of "Pygame" is missing. I downloaded the other version that was here (version 1.5) https://www.mediafire.com/folder/viiyk6xdjiyhx/FNF_in_python and it says the same thing.

**Comment by EndersteveGamer** [comment]
Are you sure you are running the version of Python that has Pygame installed?

**Comment by Brad2024** [comment]
I got it installed, but now the thing says "Traceback (most recent call last):
  File "D:\miscellaneous\FNF in Python v1.5\FNF in Python\Main menu.py", line 1, in <module>
    from _pyache_ import *
ModuleNotFoundError: No module named '_pyache_'"

**Comment by EndersteveGamer** [comment]
Seems like you modified the code accidentally or something because it's not supposed to be "pyache" but "pygame"

**Comment by EndersteveGamer** [comment]
Make sure you click on the game when it starts, sometimes it doesn't get focus and typing modifies the code

**Comment by Brad2024** [comment]
Thanks for the help. It turns out that I did modify the game to try and solve the issue of me not having pygame. But now the problem is fixed.
