### ISSUE TITLE
dev help

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [EndersteveGamer/Friday-night-funkin-with-Pygame#14]
Sorry not an bug issue,
I was trying to understand how this program works, but I realized it only responds when sound is present, which made me sad. I played the game, attempting wrong moves, but the player didn't respond or make a sound until the right moment.

The thing is, I'm trying to create a game similar to Friday Night Funkin' where I can provide a YouTube link, generate .mp3 files, auto-generate beat maps, and make it playable. I already have some other games for that purpose:

OpenJSAB (https://gitlab.com/krafi/openjsab): It's a clone of "Just Shapes and Beats" where you can provide a YouTube link and play using Pygame.

InviOSU (https://gitlab.com/krafi/inviOSU): An Osu! clone that auto-generates maps from YouTube links with invisible backgrounds, created with PyQt.

**Comment by View-my-Git-Lab-krafi** [comment]
my question is is it possible to do something like that in this project ? maybe not how write songData.json  and chart.json

**Comment by View-my-Git-Lab-krafi** [comment]
or should i try to make from start ? https://www.youtube.com/watch?v=u4Iq4niauCo&ab_channel=tested

**Comment by EndersteveGamer** [comment]
The songData.json contains all data related to which character to use, where to display them, which background to use etc...
The chart.json has all the data of the arrows, when they should be pressed, if it is a left arrow, a long arrow etc...
I don't remember exactly how the chart.json is organised, when I'm back on my computer I'll reply with how it works

**Comment by View-my-Git-Lab-krafi** [comment]
Add the chart of your song in the folder and rename it "chart.json" does it mean rename your song.mp3 or song.wav

**Comment by View-my-Git-Lab-krafi** [comment]
For now your game have enough degine enemy , background maps . I just want to create a tools for auto-generate from the song and giving youtube link feature , for that maybe i dont need to modify this project code will you please help me for this task ?? could you just make a short video how to create new lvl of this game ?

**Comment by View-my-Git-Lab-krafi** [comment]
https://github.com/EndersteveGamer/Friday-night-funkin-with-Pygame/issues/14

https://www.youtube.com/watch?v=cvojJoBlbGk&ab_channel=JHP

**Comment by View-my-Git-Lab-krafi** [comment]
https://www.youtube.com/watch?v=cvojJoBlbGk&ab_channel=JHP

**Comment by EndersteveGamer** [comment]
The chart.json files has a lot of things that are unused by my engine but used in the real Friday Night Funkin, but the most important thing is :
```
{
   "song": {
      "notes": [
         *note sections*
      ],
      "bpm": *the BPM of the song, used for the animations*
   }
}
```

A section looks like:
```
{
   "mustHitSection": *true or false*,
   "sectionNotes": [
         [
            *the time in milliseconds when you have to hit the note*,
            *the column of the note*,
            *another data, rarely used, mostly 0*
         ],
         ...
    ]
}
```

Note 1:  that all the charts from Friday Night Funkin mods will work in my engine (even if all the data from the charts are not used), so the way that the charts work is not specific to my engine

Note 2: I don't really know why the notes are divided in sections, I guess that it's due to the default Friday Night Funkin Chart editor editing notes section by section

There are two main ways to represent the charts (I found them both on different mods), and my engine is compatible with both of them:
- You can use the "mustHitSection" parameter on the different sections. Then the columns will be:
    - If the section has "mustHitSection" to `true`, then it's the player's turn:
       - 0: Player left
       - 1: Player down
       - 2: Player up
       - 3: Player right
       - 4: Opponent left
       - 5: Opponent down
       - 6: Opponent up
       - 7: Opponent right
    - If the section has "mustHitSection " to false, then it's the opponent's turn:
       - 0: Opponent down
       - 1: Opponent left
       - 2: Opponent up
       - 3: Opponent right
       - 4: Player left
       - 5: Player down
       - 6: Player up
       - 7: Player right
- You can choose to not use "mustHitSection" (then it will be always `false`). Then the columns will be:
   - 0: Player left
   - 1: Player down
   - 2: Player up
   - 3: Player right
   - 4: Opponent down
   - 5: Opponent left
   - 6: Opponent up
   - 7: Opponent right

You can find all the infos of the columns as a commentary in Game.py on line 393

**Comment by View-my-Git-Lab-krafi** [comment]
I see so some parts of  Friday Night Funkin is written in python thats why you are confused . so its possible to detect beats from a song file maybe .mp3 or .wav and auto generate . i need to play around more to understand 


```
cd assets/Musics/
Absent/                 Censory\ overload/      Expurgation/            Monochrome/             Power\ outage/          Sorrow/                 You\ can\'t\ run/     
Aurora/                 Chartering/             Ghost/                  Nacreous\ snowmelt/     Quaoar/                 Sunshine/                                     
Ballistic/              Crystallized/           Ghoul/                  newrun/                 Rainbow\ trololo/       Sussy\ wussy/                                 
Ballistic\ HQ/          Ectospasm/              Hellclown/              Nightmare\ run/         Reminisce/              Trouble/                                      
Black\ sun/             Ectospasm\ apocalypse/  Last\ reel/             No\ head\ red/          Run/                    Uncertain\ demise/                            
Burning\ in\ hell/      Endless/                Left\ unchecked/        Parasite/               Satisfracture/          Unhinged/  
```

**as you can see there are many folder i copy a lvl that "Absent/" to "newlvl/"**
but it didnt show up on the game

**Comment by EndersteveGamer** [comment]
You have to add the name of your level in MusicList.json for it to appear

**Comment by EndersteveGamer** [comment]
It looks like you don't need help anymore, so I am closing this

**Comment by View-my-Git-Lab-krafi** [comment]
Thanks a lot to you for helping me learn about fnf gameplay stricture , the thing is fnf is predicted game it's an bad idea I want to adjust any song with fnf it's not good , also fnf is special for that voice I believe, 
And generating maps form song is horrible idea ,
By the way today I create a tool that analysis Bass ,Midrange ,Treble,Tempo, Dynamics Timbre (MFCCs)", Pattern  you can create json or real time view there are a issue like for those calculation music get stuck not well optimize, anyway no plan with this code just done some experiment.
https://gitlab.com/krafi/music-analyse

 there is an ai tool called osu-dreamer it create OSU maps using mp3 it's pretty good I will say  there is OSU!mania inside OSU game kinda fnf kinda game .

And last some days I was working with open source piano tails game  ( sorry not pushed on git)

Another game called " just shapes and beats" type game if you know 
https://gitlab.com/krafi/openjsab

Sorry I couldn't contribute on your code , I just realized it will not work..
And this game development I do is just for hobby have a great day ☺️💓
