### ISSUE TITLE
Characters in the game for version 1.6 are not appearing (Python version not EXE version)

### ISSUE THREAD

**Issue by Quinte1000** [EndersteveGamer/Friday-night-funkin-with-Pygame#2]
The characters are not appearing up when I play a song

**Comment by EndersteveGamer** [comment]
Characters not appearing means that a file is missing or informations stored in the songData.json file is incorrect. This is working for me, what song were you playing, was it a default one or one that you modded into the game? Make sure you don't modify the code, as it may cause this issue too

**Comment by EndersteveGamer** [comment]
Make sure you also play with a 1080p resolution, as resolutions inferior to that may cause issues due to characters not placed correctly. If you play with a resolution inferior to 1080p, the opponent's side will not show up, as it would be displayed on top of the player's side because it has no space to show up

**Comment by Quinte1000** [comment]
I did not modify the game, but for some reason, the characters only appeared in the exe version.
Btw all of the characters in all of the songs did not appear and I was using fnf python version 1.6

**Comment by EndersteveGamer** [comment]
Weird, at worked for me, and the exe has the exact same code than the python version

**Comment by EndersteveGamer** [comment]
Try redownloading the game

**Comment by Quinte1000** [comment]
ok

**Comment by Quinte1000** [comment]
I downloaded the game again but I still have the same issue.

**Comment by EndersteveGamer** [comment]
I redownloaded the game and the Python version runs fine, characters are appearing. But after testing I found out that the game completely glitches when using EduPython, so I recommend using Pycharm instead. I think it has to do with how EduPython handles float numbers (or is it the Python version EduPython is using? I know EduPython is using Conda as Python version)

**Comment by EndersteveGamer** [comment]
Closing this issue as I fixed it and it will be fixed in 1.7. Running the game in EduPython breaks everything, but running it with Pycharm works fine
